### ISSUE TITLE
希望您可以提供一份通用格式的思维导图

### ISSUE THREAD

**Issue by bd-dxg** [itchaox/Vue2-mind-map#1]
希望您可以提供一份通用格式的思维导图 ， 减少沟通和交流的成本 ，方便自己 也方便他人

**Comment by itchaox** [comment]
可以，我去找一下怎么转换格式，好了给你讲

**Comment by itchaox** [comment]
- 你好，我刚尝试了将该思维导图转成 XMind 格式，但是没成功，转换成 XMind 格式需要会员，我就没转！
- 但是新增了 PDF 格式的思维导图和在线预览思维导图的地址！【但PDF格式展示的是全部节点，不便观看】
- 建议还是采取下载MindMaster文件再打开仓库中的 .emmx ，这样结构会更加清晰一点！
- itchao
- 2021年10月31日16:01:01
